site_name: Documentation
docs_dir: 'docs'
site_author: Ty Myrddin
repo_url: https://github.com/tymyrddin/documentation
edit_uri: edit/main/Documentation/docs/
theme:
    name: readthedocs
    custom_dir: custom_theme/
    include_homepage_in_sidebar: False
    prev_next_buttons_location: 'bottom'
    titles_only: True
    logo: img/logo.png
    style_external_links: True
nav:
    - Home: 'index.md'
    - 'code-comments.md'
    - 'quickstarts.md'
    - 'user-manuals.md'
    - 'troubleshooting-guides.md'
    - 'automated-tests.md'
    - 'commit-messages.md'
    - 'pr-descriptions.md'
    - 'automated-docs.md'
    - 'error-messages.md'
extra_css:
    - css/extra.css
