site_name: Documentation
docs_dir: 'docs'
site_author: Ty Myrddin
repo_url: https://github.com/tymyrddin/documentation
edit_uri: edit/main/docs/
theme:
    name: readthedocs
    custom_dir: custom_theme/
nav:
    - Home: 'index.md'
    - 'code-comments.md'
    - 'quickstarts.md'
    - 'user-manuals.md'
    - 'troubleshooting-guides.md'
    - 'automated-tests.md'
    - 'commit-messages.md'
    - 'pr-descriptions.md'
    - 'automated-docs.md'
    - 'error-messages.md'
extra_css:
    - css/extra.css
