name: Publish Documentation using MkDocs

on:
  push:
    branches:
      - 'main'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install mkdocs
    - name: Build documentation
      run: |
        cd Documentation
        mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/site/
        force_orphan: true